# Generated by Django 4.2.1 on 2023-05-27 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemistry',
            fields=[
                ('qno', models.IntegerField(primary_key=True, serialize=False)),
                ('qname', models.CharField(max_length=500)),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('qclass', models.CharField(max_length=1)),
                ('a', models.CharField(default='SOME STRING', max_length=100)),
                ('b', models.CharField(default='SOME STRING', max_length=100)),
                ('c', models.CharField(default='SOME STRING', max_length=100)),
                ('d', models.CharField(default='SOME STRING', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Math',
            fields=[
                ('qno', models.IntegerField(primary_key=True, serialize=False)),
                ('qname', models.CharField(max_length=500)),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('qclass', models.CharField(max_length=1)),
                ('a', models.CharField(default='SOME STRING', max_length=100)),
                ('b', models.CharField(default='SOME STRING', max_length=100)),
                ('c', models.CharField(default='SOME STRING', max_length=100)),
                ('d', models.CharField(default='SOME STRING', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Physics',
            fields=[
                ('qno', models.IntegerField(primary_key=True, serialize=False)),
                ('qname', models.CharField(max_length=500)),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('qclass', models.CharField(max_length=1)),
                ('a', models.CharField(default='SOME STRING', max_length=100)),
                ('b', models.CharField(default='SOME STRING', max_length=100)),
                ('c', models.CharField(default='SOME STRING', max_length=100)),
                ('d', models.CharField(default='SOME STRING', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reset',
            fields=[
                ('sid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('srollno', models.CharField(max_length=25)),
                ('stoken', models.CharField(max_length=100)),
                ('spass', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('sname', models.CharField(max_length=50)),
                ('srollno', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('spass', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Signup1',
            fields=[
                ('sname', models.CharField(max_length=50)),
                ('srollno', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('spass', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('srollno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
                ('sattempt', models.IntegerField(default=0)),
                ('spoints', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('empid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=50)),
                ('esubject', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSignup',
            fields=[
                ('empid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=50)),
                ('epass', models.CharField(max_length=150)),
                ('esubject', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('qno', models.IntegerField(primary_key=True, serialize=False)),
                ('qname', models.CharField(max_length=500)),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('qclass', models.CharField(max_length=1)),
                ('a', models.CharField(default='SOME STRING', max_length=100)),
                ('b', models.CharField(default='SOME STRING', max_length=100)),
                ('c', models.CharField(default='SOME STRING', max_length=100)),
                ('d', models.CharField(default='SOME STRING', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('resultid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('attempt', models.IntegerField()),
                ('right', models.IntegerField()),
                ('wrong', models.IntegerField()),
                ('points', models.FloatField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testweb.student')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicsResult',
            fields=[
                ('resultid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('attempt', models.IntegerField()),
                ('right', models.IntegerField()),
                ('wrong', models.IntegerField()),
                ('points', models.FloatField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testweb.student')),
            ],
        ),
        migrations.CreateModel(
            name='MathResult',
            fields=[
                ('resultid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('attempt', models.IntegerField()),
                ('right', models.IntegerField()),
                ('wrong', models.IntegerField()),
                ('points', models.FloatField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testweb.student')),
            ],
        ),
        migrations.CreateModel(
            name='ChemistryResult',
            fields=[
                ('resultid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('attempt', models.IntegerField()),
                ('right', models.IntegerField()),
                ('wrong', models.IntegerField()),
                ('points', models.FloatField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testweb.student')),
            ],
        ),
    ]
